// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// find_local_maxima_cpp
LogicalMatrix find_local_maxima_cpp(NumericMatrix z, int neigh_size);
RcppExport SEXP _AutoSpectralRcpp_find_local_maxima_cpp(SEXP zSEXP, SEXP neigh_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type neigh_size(neigh_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(find_local_maxima_cpp(z, neigh_size));
    return rcpp_result_gen;
END_RCPP
}
// optimize_unmix
arma::mat optimize_unmix(const arma::mat& raw_data, const arma::mat& unmixed_init, const arma::mat& base_spectra, const arma::vec& pos_thresholds, CharacterVector fluor_names, CharacterVector optimize_fluors, CharacterVector all_fluorophores, List variants, List delta_list, List delta_norms, int k, int nthreads);
RcppExport SEXP _AutoSpectralRcpp_optimize_unmix(SEXP raw_dataSEXP, SEXP unmixed_initSEXP, SEXP base_spectraSEXP, SEXP pos_thresholdsSEXP, SEXP fluor_namesSEXP, SEXP optimize_fluorsSEXP, SEXP all_fluorophoresSEXP, SEXP variantsSEXP, SEXP delta_listSEXP, SEXP delta_normsSEXP, SEXP kSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type raw_data(raw_dataSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type unmixed_init(unmixed_initSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type base_spectra(base_spectraSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pos_thresholds(pos_thresholdsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type fluor_names(fluor_namesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type optimize_fluors(optimize_fluorsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type all_fluorophores(all_fluorophoresSEXP);
    Rcpp::traits::input_parameter< List >::type variants(variantsSEXP);
    Rcpp::traits::input_parameter< List >::type delta_list(delta_listSEXP);
    Rcpp::traits::input_parameter< List >::type delta_norms(delta_normsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_unmix(raw_data, unmixed_init, base_spectra, pos_thresholds, fluor_names, optimize_fluors, all_fluorophores, variants, delta_list, delta_norms, k, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// poisson_irls_rcpp_parallel
arma::mat poisson_irls_rcpp_parallel(const arma::mat& raw_data_in, const arma::mat& spectra, const arma::mat& beta_init_in, const int maxit, const double tol, const int n_threads, const double divergence_threshold, const int max_halving_steps);
RcppExport SEXP _AutoSpectralRcpp_poisson_irls_rcpp_parallel(SEXP raw_data_inSEXP, SEXP spectraSEXP, SEXP beta_init_inSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP n_threadsSEXP, SEXP divergence_thresholdSEXP, SEXP max_halving_stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type raw_data_in(raw_data_inSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type spectra(spectraSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta_init_in(beta_init_inSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const double >::type divergence_threshold(divergence_thresholdSEXP);
    Rcpp::traits::input_parameter< const int >::type max_halving_steps(max_halving_stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(poisson_irls_rcpp_parallel(raw_data_in, spectra, beta_init_in, maxit, tol, n_threads, divergence_threshold, max_halving_steps));
    return rcpp_result_gen;
END_RCPP
}
// unmix_af_fluorophores
Rcpp::List unmix_af_fluorophores(const arma::mat& raw_data, const arma::mat& fluor_spectra, const arma::mat& af_spectra, int n_threads);
RcppExport SEXP _AutoSpectralRcpp_unmix_af_fluorophores(SEXP raw_dataSEXP, SEXP fluor_spectraSEXP, SEXP af_spectraSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type raw_data(raw_dataSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type fluor_spectra(fluor_spectraSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type af_spectra(af_spectraSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(unmix_af_fluorophores(raw_data, fluor_spectra, af_spectra, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// unmix_af_residuals
Rcpp::List unmix_af_residuals(const arma::mat& raw_data, const arma::mat& fluor_spectra, const arma::mat& af_spectra, int n_threads);
RcppExport SEXP _AutoSpectralRcpp_unmix_af_residuals(SEXP raw_dataSEXP, SEXP fluor_spectraSEXP, SEXP af_spectraSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type raw_data(raw_dataSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type fluor_spectra(fluor_spectraSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type af_spectra(af_spectraSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(unmix_af_residuals(raw_data, fluor_spectra, af_spectra, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// unmix_autospectral_pipeline_cpp
arma::mat unmix_autospectral_pipeline_cpp(arma::mat raw_data_in, const arma::mat& spectra, const arma::mat& af_spectra, const CharacterVector& fluor_names, const CharacterVector& optimize_fluors, const arma::vec& pos_thresholds, const List& variants, const List& delta_list, const List& delta_norms, int k_opt, int n_threads, bool optimize, bool use_dist0);
RcppExport SEXP _AutoSpectralRcpp_unmix_autospectral_pipeline_cpp(SEXP raw_data_inSEXP, SEXP spectraSEXP, SEXP af_spectraSEXP, SEXP fluor_namesSEXP, SEXP optimize_fluorsSEXP, SEXP pos_thresholdsSEXP, SEXP variantsSEXP, SEXP delta_listSEXP, SEXP delta_normsSEXP, SEXP k_optSEXP, SEXP n_threadsSEXP, SEXP optimizeSEXP, SEXP use_dist0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type raw_data_in(raw_data_inSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type spectra(spectraSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type af_spectra(af_spectraSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type fluor_names(fluor_namesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type optimize_fluors(optimize_fluorsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pos_thresholds(pos_thresholdsSEXP);
    Rcpp::traits::input_parameter< const List& >::type variants(variantsSEXP);
    Rcpp::traits::input_parameter< const List& >::type delta_list(delta_listSEXP);
    Rcpp::traits::input_parameter< const List& >::type delta_norms(delta_normsSEXP);
    Rcpp::traits::input_parameter< int >::type k_opt(k_optSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type optimize(optimizeSEXP);
    Rcpp::traits::input_parameter< bool >::type use_dist0(use_dist0SEXP);
    rcpp_result_gen = Rcpp::wrap(unmix_autospectral_pipeline_cpp(raw_data_in, spectra, af_spectra, fluor_names, optimize_fluors, pos_thresholds, variants, delta_list, delta_norms, k_opt, n_threads, optimize, use_dist0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AutoSpectralRcpp_find_local_maxima_cpp", (DL_FUNC) &_AutoSpectralRcpp_find_local_maxima_cpp, 2},
    {"_AutoSpectralRcpp_optimize_unmix", (DL_FUNC) &_AutoSpectralRcpp_optimize_unmix, 12},
    {"_AutoSpectralRcpp_poisson_irls_rcpp_parallel", (DL_FUNC) &_AutoSpectralRcpp_poisson_irls_rcpp_parallel, 8},
    {"_AutoSpectralRcpp_unmix_af_fluorophores", (DL_FUNC) &_AutoSpectralRcpp_unmix_af_fluorophores, 4},
    {"_AutoSpectralRcpp_unmix_af_residuals", (DL_FUNC) &_AutoSpectralRcpp_unmix_af_residuals, 4},
    {"_AutoSpectralRcpp_unmix_autospectral_pipeline_cpp", (DL_FUNC) &_AutoSpectralRcpp_unmix_autospectral_pipeline_cpp, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_AutoSpectralRcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
