# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

assign_af_fluor <- function(raw_data, spectra, af_spectra, n_threads = 4L) {
    .Call(`_AutoSpectralRcpp_assign_af_fluor`, raw_data, spectra, af_spectra, n_threads)
}

#' Bin a spectral expression matrix into a 2D count matrix
#'
#' Takes an n_events x n_channels matrix of already biexp-transformed values
#' and bins them into an n_y x n_x count matrix. Loops column-major to match
#' R's memory layout and avoid cache misses.
#'
#' @param data NumericMatrix of biexp-transformed expression values,
#'   n_events rows x n_channels (n_x) columns.
#' @param y_breaks NumericVector of length n_y + 1, uniformly spaced break
#'   points spanning the y-axis range. Produced by seq(y_min, y_max,
#'   length.out = n_y + 1).
#' @param n_y Integer number of y bins.
#'
#' @return IntegerMatrix of counts, n_y rows x n_x columns.
#'
#' @export
bin_matrix_cpp <- function(data, y_breaks, n_y) {
    .Call(`_AutoSpectralRcpp_bin_matrix_cpp`, data, y_breaks, n_y)
}

#' Fast Kernel Density Estimation in 2D
#'
#' @param x Numeric vector of x-values (typically FSC-A)
#' @param y Numeric vector of y-values (typically SSC-A)
#' @param n Number of grid points for both x and y (recommend 100)
#' @param h Vector of bandwidths for x and y (recommed 0.1*bandwidth.nrd)
#' @param x_limits Limits of the data in the x coordinates
#' @param y_limits Limits of the data in the y coordinates
#' @export
fast_kde2d_cpp <- function(x, y, n, h, x_limits, y_limits) {
    .Call(`_AutoSpectralRcpp_fast_kde2d_cpp`, x, y, n, h, x_limits, y_limits)
}

fcs_rcpp_read_data <- function(file_path, byte_offset, n_row, n_par, swap, selected_cols = NULL) {
    .Call(`_AutoSpectralRcpp_fcs_rcpp_read_data`, file_path, byte_offset, n_row, n_par, swap, selected_cols)
}

fcs_rcpp_write_data <- function(file_path, header, text_segment, data_mat, swap) {
    invisible(.Call(`_AutoSpectralRcpp_fcs_rcpp_write_data`, file_path, header, text_segment, data_mat, swap))
}

#' Filter contaminant events by cosine similarity
#'
#' For each event (row) in \code{event_mat}, computes cosine similarity
#' against every spectrum (row) in \code{spectra_mat}.  Returns a logical
#' vector that is \code{TRUE} for events whose maximum cosine similarity to
#' any spectrum is strictly below \code{threshold}.
#'
#' @param event_mat   Numeric matrix; events x detectors (the unstained
#'   expression data, restricted to the spectral channels).
#' @param spectra_mat Numeric matrix; fluorophores x detectors (the reference
#'   spectra, AF rows already removed, L-inf normalised).
#' @param threshold   Numeric scalar.  Events with max cosine similarity
#'   \eqn{\geq} \code{threshold} are flagged as contaminants.
#' @return A logical vector of length \code{nrow(event_mat)}.  \code{TRUE}
#'   means the event is clean (keep); \code{FALSE} means it is a likely
#'   contaminant (remove).
#' @export
filter_contaminant_events_cpp <- function(event_mat, spectra_mat, threshold) {
    .Call(`_AutoSpectralRcpp_filter_contaminant_events_cpp`, event_mat, spectra_mat, threshold)
}

#' Find Local Maxima
#'
#' @param z Matrix of 2D density values
#' @param neigh_size Number of neighboring points to consider
#' @export
find_local_maxima <- function(z, neigh_size) {
    .Call(`_AutoSpectralRcpp_find_local_maxima`, z, neigh_size)
}

#' Batched Truncated Spillover Slope, One Source Against Every Target (C++)
#'
#' @description
#' Port of the truncated-estimator half of `.fix.envelope.slope()` --
#' `select.negative()` plus the `max.mask.passes` refinement loop plus
#' `.fix.huber.slope()` -- run for every target sharing one source's
#' abundance in a single call, instead of once per (source, target) pair.
#'
#' Every working buffer (`w`, `resid`, the selection-index scratch space) is
#' allocated once, sized to `n`, and reused across every target and every
#' mask pass; only the `ni <= n` elements actually selected for a given
#' target's current pass are touched. This is the piece that a batched pure-R
#' implementation cannot get right no matter how it is vectorised: R's
#' `sweep()` / `outer()` return fresh objects every call, so a version built
#' from them reallocates matrices sized to the full working set on every one
#' of up to `targets x mask.passes x irls.iterations` steps, several times
#' over. Batching only pays off once that allocation, and the two
#' `stats::median()` calls' R-level dispatch per iteration, are removed
#' entirely -- which needs compiled code, not a different R vectorisation.
#'
#' Reproduces `select.negative()`'s bulk cap: every bright (source-positive)
#' event is kept regardless of file size, and the origin-hugging bulk below
#' the source threshold is subsampled down to `max_truncated_events` events
#' total once the negative-selected population exceeds it. The bulk sits at
#' the origin and carries no leverage on the fitted slope, but left uncapped
#' it sets the Huber M-estimator's iterative MAD-based scale almost
#' entirely once it outnumbers the bright tail by orders of magnitude --
#' diluting the tail's relative influence and biasing the fitted slope
#' toward zero. Each target gets its own `std::mt19937` stream, seeded from
#' `seed` and reused across passes (not reseeded per pass), so the sampling
#' is reproducible under R's `set.seed()` and identical regardless of
#' `n_threads` -- a target's subsample depends only on its own seed, never
#' on which thread happened to process it. Not bit-identical to
#' `.fix.envelope.slope()`, which draws its bulk subsample from a single
#' shared RNG stream advanced pair by pair, but statistically equivalent to
#' it.
#'
#' @param x Numeric vector, length `n`, the shared source abundance.
#' @param Y Numeric matrix, `n x m`, one column per target.
#' @param Threshold_target Numeric matrix, `n x m`, per-event per-target
#'   positivity boundary.
#' @param threshold_source Numeric vector, length `n`, the source's own
#'   per-event positivity boundary. Recycle to length `n` on the R side
#'   before calling.
#' @param start_slope Numeric vector, length `m`, per-target warm starts.
#' @param seed Integer vector, length `m`, one RNG seed per target, drawn
#'   from R's ambient RNG stream so a caller's `set.seed()` covers this
#'   call.
#' @param max_coefficient double, largest accepted residual coefficient.
#'   Default `0.2`.
#' @param max_mask_passes int, refinement passes after the initial fit.
#'   Default `3`.
#' @param mask_tolerance double, relative change below which a pass is
#'   treated as settled and refinement stops early. Default `0.05`.
#' @param min_events int, minimum selected events for a fit. Default `200`.
#' @param max_truncated_events int, cap on the events used for the robust
#'   fit. Everything above the source threshold is kept and the negative
#'   bulk below it is subsampled. Default `20000`.
#' @param k double, Huber tuning constant. Default `1.345`.
#' @param max_iter int, maximum IRLS iterations per fit. Default `100`.
#' @param tol double, IRLS relative coefficient-change tolerance. Default
#'   `1e-4`.
#' @param n_threads int, OpenMP threads to split targets across. Default
#'   `1` (serial). Every target's fit reads only its own column of `Y` and
#'   `Threshold_target` and writes only its own output slot, so this is
#'   embarrassingly parallel across targets -- but only raise it when this
#'   call is not itself already running inside another parallel context
#'   (`mclapply()` over samples, say). Oversubscribing cores that way is
#'   the same failure mode `RhpcBLASctl::blas_set_num_threads(1)` already
#'   guards against for BLAS inside forked workers elsewhere in this
#'   package -- one source of truth for how many cores are in play at a
#'   time, not two competing ones.
#'
#' @return A list with `slope` (numeric, length `m`, `NA` where the selected
#'   population never reached `min_events`) and `n` (integer, length `m`,
#'   the final pass's selected event count, for `span`/diagnostic use back
#'   in R).
#'
#' @export
fix_envelope_truncated_batch_rcpp <- function(x, Y, Threshold_target, threshold_source, start_slope, seed, max_coefficient = 0.2, max_mask_passes = 3L, mask_tolerance = 0.05, min_events = 200L, max_truncated_events = 20000L, k = 1.345, max_iter = 100L, tol = 1e-4, n_threads = 1L) {
    .Call(`_AutoSpectralRcpp_fix_envelope_truncated_batch_rcpp`, x, Y, Threshold_target, threshold_source, start_slope, seed, max_coefficient, max_mask_passes, mask_tolerance, min_events, max_truncated_events, k, max_iter, tol, n_threads)
}

#' Huber-Weighted IRLS Slope (C++)
#'
#' @description
#' Line-for-line port of AutoSpectral's `.fix.huber.slope()`
#' (fix_my_unmix.R): a Huber-weighted, iteratively reweighted least squares
#' fit of `y` on `x`, one predictor with an intercept. Every step is the
#' same closed-form weighted mean/variance update the R version uses - no
#' BLAS call here either, only the iteration loop and the two `median()`
#' calls per iteration moving out of the R interpreter, which is what
#' `.fix.envelope.slope()`'s call volume (every panel pair, every mask
#' pass, every spillover-estimator iteration, every inner-loop pass) makes
#' worth paying for. All scratch buffers are allocated once, outside the
#' iteration loop, and reused every iteration.
#'
#' On non-convergence this returns a zero slope rather than falling back to
#' OLS, matching the R version: a coefficient this function cannot pin down
#' is exactly the case the caller needs to see as untrustworthy.
#'
#' @param x,y Numeric vectors, the predictor and response. Must be the same
#'   length.
#' @param k Numeric, the Huber tuning constant. Default `1.345`.
#' @param max_iter Integer, maximum IRLS iterations. Default `100`.
#' @param tol Numeric, relative coefficient-change convergence tolerance.
#'   Default `1e-4`.
#' @param start Optional numeric vector `c(intercept, slope)`, a warm
#'   start. When supplied, the first iteration's weights come from its
#'   residuals instead of OLS weights. Default `NULL`.
#'
#' @return Numeric vector `c(intercept, slope)`.
#'
#' @export
fix_huber_slope_rcpp <- function(x, y, k = 1.345, max_iter = 100L, tol = 1e-4, start = NULL) {
    .Call(`_AutoSpectralRcpp_fix_huber_slope_rcpp`, x, y, k, max_iter, tol, start)
}

optimize_unmix <- function(raw_data, unmixed_init, base_spectra, pos_thresholds, fluor_names, optimize_fluors, all_fluorophores, variants, delta_list, delta_norms, k = 10L, nthreads = 1L) {
    .Call(`_AutoSpectralRcpp_optimize_unmix`, raw_data, unmixed_init, base_spectra, pos_thresholds, fluor_names, optimize_fluors, all_fluorophores, variants, delta_list, delta_norms, k, nthreads)
}

#' Poisson IRLS Parallel
#'
#' @export
#' @param raw_data_in matrix of cells x detectors
#' @param spectra matrix of fluorophores x detectors
#' @param beta_init_in initial unmixed matrix of cells x fluorophores
#' @param maxit maximum number of IRLS iterations
#' @param tol convergence tolerance
#' @param n_threads number of threads to use (OpenMP)
#' @param divergence_threshold maximum ratio of a cell's deviance to its
#' initial (WLS-seeded) deviance before that iteration is treated as
#' divergent and the cell reverts towards `beta_init`
#' @param max_halving_steps maximum number of halving steps to use to approach
#' convergence
#' @param noise_floor Numeric scalar or per-detector vector, default `125`.
#' Lower clamp on the denominator of the IRLS weight, preventing
#' \eqn{w_d \to \infty} for near-dark channels. Signal units, same
#' convention as `noise.floor` elsewhere in the package.
#' @param final_validation_ratio Numeric, default `1.5`. A cell's final
#' deviance is allowed to exceed its initial (WLS-seeded) deviance by at
#' most this multiple before the cell is reverted to `beta_init`.
#' @return A list with `beta` (matrix of cells x fluorophores) and
#' `converged` (numeric vector, one entry per cell: `0` converged within
#' `tol`, `1` reverted mid-loop due to divergence, `2` reverted because the
#' final fit produced an invalid (near-zero or negative) predicted mean,
#' `3` reverted because final deviance exceeded `final_validation_ratio`
#' times initial deviance, `4` reached `maxit` without meeting `tol` but the
#' last accepted step was kept)
poisson_irls_rcpp_parallel <- function(raw_data_in, spectra, beta_init_in, maxit = 25L, tol = 1e-6, n_threads = 1L, divergence_threshold = 1e4, max_halving_steps = 20L, noise_floor = NULL, final_validation_ratio = 1.5) {
    .Call(`_AutoSpectralRcpp_poisson_irls_rcpp_parallel`, raw_data_in, spectra, beta_init_in, maxit, tol, n_threads, divergence_threshold, max_halving_steps, noise_floor, final_validation_ratio)
}

#' Train a Self-Organizing Map with batch updates (OpenMP-accelerated)
#'
#' Port of EmbedSOM's batch SOM (\code{EmbedSOM::SOM(..., batch = TRUE)}),
#' intended as the clustering engine behind \code{get.af.spectra()} and
#' \code{get.fluor.variants()} without requiring EmbedSOM as a dependency.
#'
#' This is a different algorithm from the retired online \code{som_train_cpp()}
#' (one weighted-average update per epoch over the whole dataset, rather than
#' one small update per randomly-drawn event) and does not reproduce
#' \code{FlowSOM::SOM()}'s per-event codebook trajectory bit-for-bit. It is
#' validated instead against \code{EmbedSOM::SOM(..., batch = TRUE)} output
#' for a fixed seed.
#'
#' @param data Numeric matrix, training events x features (column-major).
#' @param init_codes Numeric matrix, initial codebook (rows = SOM nodes),
#'   same columns as \code{data}. Chosen in R (e.g. a random sample of
#'   \code{data} rows) so that \code{set.seed()} controls it.
#' @param nhbrdist Numeric matrix (ncodes x ncodes), grid neighbourhood
#'   distances.
#' @param radii Numeric vector, one neighbourhood radius per epoch --
#'   \code{length(radii)} is the number of epochs (there is no separate
#'   \code{rlen}). Typically a decreasing schedule built in R, e.g.
#'   \code{seq(radius_start, radius_end, length.out = rlen)}. Must stay
#'   strictly positive: the neighbourhood kernel is
#'   \code{exp(-d^2 / radius^2)}, and a radius of exactly 0 would starve
#'   every node outside the exact best-matching unit (guarded internally
#'   via \code{min_radius}, but avoid relying on that guard).
#' @param dist Integer 1:4, distance function (1 manhattan, 2 euclidean,
#'   3 chebyshev, 4 cosine). Default 2.
#' @param n_threads Integer, OpenMP threads. Default 0 (all available
#'   cores, via \code{omp_get_max_threads()}).
#' @return Numeric matrix, the trained codebook (ncodes x features).
#' @export
som_train_batch_cpp <- function(data, init_codes, nhbrdist, radii, dist = 2L, n_threads = 0L) {
    .Call(`_AutoSpectralRcpp_som_train_batch_cpp`, data, init_codes, nhbrdist, radii, dist, n_threads)
}

#' Map data onto a trained SOM codebook (OpenMP-accelerated)
#'
#' For each row of \code{data}, finds the nearest code in \code{codes}.
#' Fully data-parallel across events.
#'
#' @param data Numeric matrix, events x features (same column order as
#'   \code{codes}).
#' @param codes Numeric matrix, SOM codebook (nodes x features).
#' @param dist Integer 1:4, distance function (see \code{som_train_cpp}).
#' @param n_threads Integer, OpenMP threads. Default 1.
#' @return Numeric matrix, 2 columns: nearest code id (1-based) and distance
#'   to that code, one row per event.
#' @export
map_data_to_codes_cpp <- function(data, codes, dist = 2L, n_threads = 1L) {
    .Call(`_AutoSpectralRcpp_map_data_to_codes_cpp`, data, codes, dist, n_threads)
}

unmix_af_fluorophores <- function(raw_data, fluor_spectra, af_spectra, n_threads = 4L) {
    .Call(`_AutoSpectralRcpp_unmix_af_fluorophores`, raw_data, fluor_spectra, af_spectra, n_threads)
}

unmix_af_residuals <- function(raw_data, fluor_spectra, af_spectra, n_threads = 4L) {
    .Call(`_AutoSpectralRcpp_unmix_af_residuals`, raw_data, fluor_spectra, af_spectra, n_threads)
}

unmix_autospectral_joint_cpp <- function(raw_data_in, spectra, af_spectra, fluor_names, pos_thresholds, variants_list, delta_list, n_passes = 2L, n_threads = 1L, cell_weight = FALSE, noise_floor = NULL, alpha = 0.5, collinear_thresh = 0.5, joint_pair_resolution = TRUE, n_af_passes = 1L, refine_af_quantile = 0.5) {
    .Call(`_AutoSpectralRcpp_unmix_autospectral_joint_cpp`, raw_data_in, spectra, af_spectra, fluor_names, pos_thresholds, variants_list, delta_list, n_passes, n_threads, cell_weight, noise_floor, alpha, collinear_thresh, joint_pair_resolution, n_af_passes, refine_af_quantile)
}

unmix_autospectral_pipeline_cpp <- function(raw_data_in, spectra, af_spectra, fluor_names, optimize_fluors, pos_thresholds, variants, delta_list, delta_norms, k_opt = 1L, n_threads = 1L, optimize = TRUE, use_dist0 = TRUE) {
    .Call(`_AutoSpectralRcpp_unmix_autospectral_pipeline_cpp`, raw_data_in, spectra, af_spectra, fluor_names, optimize_fluors, pos_thresholds, variants, delta_list, delta_norms, k_opt, n_threads, optimize, use_dist0)
}

