# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

optimize_unmix_rcpp_exact <- function(remaining_raw, unmixed, spectra, pos_thresholds, optimize_idx_r, variantsList, weights, weighted = FALSE, nthreads = 1L) {
    .Call(`_AutoSpectralRcpp_optimize_unmix_rcpp_exact`, remaining_raw, unmixed, spectra, pos_thresholds, optimize_idx_r, variantsList, weights, weighted, nthreads)
}

optimize_unmix_rcpp_fast <- function(remaining_raw, unmixed, spectra, pos_thresholds, optimize_idx_r, variantsList, weights, weighted = FALSE, nthreads = 1L) {
    .Call(`_AutoSpectralRcpp_optimize_unmix_rcpp_fast`, remaining_raw, unmixed, spectra, pos_thresholds, optimize_idx_r, variantsList, weights, weighted, nthreads)
}

optimize_unmix_rcpp_woodbury <- function(remaining_raw, unmixed, spectra, pos_thresholds, optimize_idx_r, variantsList, weights, weighted = FALSE, nthreads = 1L, singular_tol = 1e-8) {
    .Call(`_AutoSpectralRcpp_optimize_unmix_rcpp_woodbury`, remaining_raw, unmixed, spectra, pos_thresholds, optimize_idx_r, variantsList, weights, weighted, nthreads, singular_tol)
}

poisson_irls_rcpp_parallel <- function(raw_data_in, spectra, beta_init_in, maxit = 25L, tol = 1e-6, n_threads = 1L, divergence_threshold = 1e4) {
    .Call(`_AutoSpectralRcpp_poisson_irls_rcpp_parallel`, raw_data_in, spectra, beta_init_in, maxit, tol, n_threads, divergence_threshold)
}

